---
version: "3.3"
services:
  dev:
    stdin_open: true
    tty: true
    build: .
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      - DISPLAY=${DISPLAY}
      - GID=${GID}
      - UID=${UID}
      - USER=${USER}
