---
version: "3.3"
services:
  # container name
  dev:

    # image that can be pulled
    image: arecarn/c-and-cpp

    # keep stdin open even if not attached
    stdin_open: true

    # allocate a pseudo-tty
    tty: true

    # build Dockerfile in the same directory as this file
    build: .

    # mount the current directory inside the container
    volumes:
      - ${PWD}:${PWD}

    # when entering the container stay in the current directory
    working_dir: ${PWD}

    # container environment variables
    environment:
      - DISPLAY=${DISPLAY}
      - GID=${GID}
      - UID=${UID}
      - USER=${USER}

    # start a bash session
    command: ["bash"]

    entrypoint: ${PWD}/entrypoint.sh
