---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arecarn/c-and-cpp
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build & Test All Targets
        run: make full
